w3c/vc-di-bbs-test-suite

- CHANGELOG.md
- README.md
- package.json
- tests/10-bbs-create.js
- tests/20-bbs-verify.js
- tests/30-bbs-interop.js
~Related to https://github.com/w3c-ccg/vc-api-test-suite-implementations/pull/92, must be merged only once the PR updating the package name gets merged.~ The PR has been merged
> Update implementations package

- .eslintrc.cjs
- .github/workflows/main.yml
- .gitignore
- CHANGELOG.md
- LICENSE
- LICENSES/BSD-3-Clause.txt
- README.md
- abstract.hbs
- package.json
- package.json.license
- respecConfig.json
- respecConfig.json.license
- tests/.eslintrc.cjs
- tests/10-bbs-create.js
- tests/20-bbs-verify.js
- tests/30-bbs-interop.js
- tests/assertions.js
- tests/didResolver.js
- tests/documentLoader.js
- tests/helpers.js
- tests/mock-data.js
- w3c.json.license
This was moved from the `w3c-ccg` organization on GitHub. This PR provides some
post move cleanup, and applies the BSD-3-Clause license (following the
[REUSE v3.0 specification](https://reuse.software/spec/)
> Cleanup and license

- .gitignore
- CHANGELOG.md
- package.json
Stores the testVectors from the `vc-di-bbs` suite in `tests/input` for later use.
> Store spec vectors

- .eslintrc.cjs
Adds an ignore for urls so that google highlight links can be posted as is.
> eslint max-len ignores urls.

- package.json
- tests/assertions.js
- tests/helpers.js
- tests/suites.js
Builds on initial config with new test assertions.
1. uses the new shouldBeBs58 and shouldBeBs64UrlNoPad assertions from di assertion
2. adds support for base64 url no pad values
3. adds a new test to the create suite.
> Update proof value test

- tests/suites.js
Adds a redundant test already covered by D.I., but ensures we match the statements from the BBS spec.
> Add redudant proof.type check from bbs spec.

- tests/assertions.js
- tests/suites/create.js
- tests/suites/verify.js
1. Adds a new option `reason` to `verificationFail` so test report can see why verification should have failed
2. Adds a new test that simulates what happens when transformation options are invalid.
Statement tested: "The transformation options MUST contain a type identifier for the cryptographic suite (type), a cryptosuite identifier (cryptosuite), and a verification method (verificationMethod). "
> Add invalid proof type, cryptosuite, & verificationMethod tests

- tests/suites/create.js
- tests/suites/verify.js
Corrects a mistake: the transformation options are for base proofs only so it moves the transformation options test to create where is actually provides some decent value. You can not verify a base proof so it's hard for this to be a verifier test.
> Move transformation options create

- package.json
- tests/15-di-bbs-verify.js
- tests/helpers.js
- tests/vc-generator/key-gen.js
Second PR in which the cryptosuite and key are provided by the suite itself.
> Pass params di verifier tests

- tests/setup.js
- tests/suites/verify.js
Improvements:
1. setup no longer has testVectors in it it just returns an object.
2. setup no longer considers VCs with just base proofs signed, base proof VCs are in base
3. setup now disambiguates between disclosed basic VCs and base VCs, simple disclosed VCs are basic
> Declutter setup

- tests/setup.js
- tests/suites/verify.js
- tests/vc-generator/generators.js
- tests/vc-generator/index.js
- tests/vc-generator/mockMethods.js
Features:
1. adds a new function to stub methods on an object.
2. stubs `createVerifyData` so that canonize can be done unsafely with empty string values.
3. adds a test for "The proof options MUST contain a type identifier for the [cryptographic suite](https://www.w3.org/TR/vc-data-integrity/#dfn-cryptosuite) (type) and MUST contain a cryptosuite identifier (cryptosuite). A proof configuration object is produced as output."
> (2) Unset proof type cryptosuite

- tests/setup.js
- tests/suites/verify.js
- tests/vc-generator/generators.js
> (3) Expand proof type and cryptosuite vectors.

- tests/assertions.js
- tests/setup.js
- tests/suites/create.js
- tests/suites/verify.js
- tests/vc-generator/generators.js
- tests/vc-generator/stubMethods.js
Features:
1. Adds support for `typeEncoders` for the cbor encoding
2. Adds a tag for decoding a custom `Uint8Array` encoder.
3. Adds a verifier test derived from a cbor encoded base proof with a invalid cbor encoded disclosed proof.
> (6) Invalid cbor tag

- tests/suites/verify.js
Changes the test title to match the latest spec text.
https://w3c.github.io/vc-di-bbs/#:~:text=If%20the%20proofValue%20string%20does%20not%20start%20with%20u%20(U%2B0075%20LATIN%20SMALL%20LETTER%20U)%2C%20indicating%20that%20it%20is%20a%20multibase%2Dbase64url%2Dno%2Dpad%2Dencoded%20value%2C%20an%20error%20MUST%20be%20raised%20and%20SHOULD%20convey%20an%20error%20type%20of%20PROOF_VERIFICATION_ERROR.
> Update test title for proofValue prefix.

- tests/setup.js
- tests/suites/verify.js
@Wind4Greg you're returning 500 for this when the proofValue prefix is invalid.
> Add test for invalid decoded proof value prefix.

- tests/setup.js
- tests/suites/verify.js
- tests/vc-generator/generators.js
- tests/vc-generator/index.js
Adds an invalid created test for the base and by extension derived proof.
TODO
> (7) Add invalid date test

- tests/suites/create.js
- Adds one new test that asserts that verificaitonMethod is a url
- Adds `this.test.link` to 1 existing test and 1 new test
> (8) Vm url test

- tests/suites/create.js
We assume if the VC verifiers locally that means it obeys all normative statements in the spec.
> Add confirming proof issuer local verifier test.

- tests/assertions.js
- tests/setup.js
- tests/suites/verify.js
- asserts on 400 or 422
- moves a test data gen from suite to setup
- adds missing normative statement
> Add non confirming processors

- package.json
- tests/vc-generator/contexts.js
- tests/vc-generator/index.js
Fixes some issues related to proof.type and the newer VC 2.0 context.
> CRITICAL: Fix safe mode bug

- tests/suites/verify.js
Removes the deprecated statement: 
> If the "cryptosuite" field is not the string "bbs-2023" an error MUST be raised
source: https://w3c.github.io/vc-di-bbs/
> Remove deprecated statement WRT to cryptosuite = bbs-2023.
